cypress-io/code-coverage

.circleci/config.yml, README.md, cypress/integration/spec.js, cypress/plugins/index.js, cypress/unit.js, package-lock.json, package.json, use-babelrc.js
- simplifies how to use `.babelrc` file
- closes #7 
- adds [@cypress/browserify-preprocessor](https://github.com/cypress-io/cypress-browserify-preprocessor#readme) as a production dependency
```js
// to use .babelrc from your plugins file add line
on('file:preprocessor', require('cypress-istanbul/use-babelrc'))
```
=> feat: add babelrc helper script

cypress/integration/spec.js, task.js, utils.js
Hi. I managed to make .vue files coverage appear in report.
The issue is the sourcemap resource path for .vue file is a crappy Webpack loaders string from vue-loader, like "cache-loader!vue-loader!file.vue?type=script,lang=ts&". 
So it's needed to clean up that path before storing the coverage report.
I've been inspired by an option on karma-coverage-istanbul-reporter doing exactly this.
=> feat: support .vue files coverage

.vscode/settings.json, README.md, middleware.js, support.js
=> feat: add server-side middleware and merge the backend coverage with frontend

.gitignore, .vscode/settings.json, cypress/integration/spec.js, utils.js
To follow-up on https://github.com/cypress-io/code-coverage/pull/17 comments.
I'm not sure it's the best way to proceed tho.
It should work on https://github.com/bahmutov/code-coverage-vue-example.
I also tried really hard to make coverage work for <template> code (through generated render function) but in the end I think it can't work until https://github.com/vuejs/vue-loader/issues/1400 is resolved so we get two distinct source-map entries for template and script parts.
=> fix: replace sourcemap's path by the corresponding absolute file path

README.md, package.json
=> chore: explain how to exclude files from coverage report

README.md, task.js
Fixes #33.
Tested locally and generate both HTML and LCOV reports, and it generated both reports to `./coverage/lcov-report`.
=> fix: update nyc reporter to lcov

README.md, cypress/plugins/index.js, use-browserify-istanbul.js
- closes #47
```js
module.exports = (on, config) => {
on('task', require('@cypress/code-coverage/task'))
on('file:preprocessor', require('@cypress/code-coverage/use-browserify-istanbul'))
}
```
Avoids using `.babelrc`
=> feat: add non .babelrc method

README.md
=> add link to the Angular + TS example, closes #51

support.js, task.js
- closes #26 
- closes #76 
Stringify coverage object before sending to avoid Cypress's "safe" stringify
=> fix: stringify coverage object to improve performance

README.md
Based on issue https://github.com/cypress-io/code-coverage/issues/97
=> Added example with vue + typescript

cypress/about.html, cypress/about.js, cypress/index.html, cypress/integration/spec.js, support.js
Save coverage for each page visited in a test by keeping a reference to the coverage for each app window loaded and then saving the coverage at the end after coverage is calculated.
The implementation in the PR keeps the behavior of saving coverage after each test since that is the current behavior and I believe it would be necessary for #4. However, I think it would also be possible to initialize the array and event listener in `before()` and only save coverage in `after()` if that is desired instead.
Closes #69
=> Save coverage for each page in a test

support.js
- closes #117 
Gives a warning if cannot find neither e2e nor unit test code coverage. The warning has a link that opens on click right inside the test runner's browser, goes to https://github.com/cypress-io/code-coverage#instrument-your-application
- if there is no e2e code coverage, but at least unit test coverage gives a "note"
=> feat: warn if missing code coverage information

.circleci/config.yml, cypress-backend.json, cypress/test-backend/spec.js, package-lock.json, package.json, support.js, test-backend/index.html, test-backend/index.js
=> Backend code coverage tests, refactor

README.md, examples/before-all-visit/cypress/integration/spec.js, support.js
- accumulates code coverage even if `cy.visit` is done once using `before` callback
- closes #137
- closes #150
Adds full example
=> feat: handle cy.visit inside before callback

.circleci/config.yml, .gitignore, README.md, examples/ts-example/.babelrc, examples/ts-example/README.md, examples/ts-example/cypress.json, examples/ts-example/cypress/integration/spec.js, examples/ts-example/cypress/plugins/index.js, examples/ts-example/cypress/support/index.js, examples/ts-example/index.html, examples/ts-example/main.ts, examples/ts-example/package.json, package-lock.json, package.json, task.js
- closes #142
- closes #165
- closes #164
- (maybe) closes #160
- closes #18
this will be a breaking dependency:
- `nyc` no longer a peer dependency
- `istanbul-lib-coverage` is no longer a peer dependency
- we changed how we call `nyc report` which could affect the results
- added `examples/ts-example`
Tested with the following example repos
- https://github.com/cypress-io/cypress-example-todomvc-redux
- https://github.com/bahmutov/testing-react
=> feat: use `nyc` NPM dependency directly without bin executable

.circleci/config.yml, examples/same-folder/.babelrc, examples/same-folder/README.md, examples/same-folder/cypress.json, examples/same-folder/cypress/fixtures/example.json, examples/same-folder/index.html, examples/same-folder/main-instrumented.js, examples/same-folder/main.js, examples/same-folder/package.json, examples/same-folder/plugins.js, examples/same-folder/spec.js, examples/same-folder/support.js, examples/same-folder/unit-utils.js, support.js
- closes #170 
Filters spec and support files better, added an example test
=> fix: improve spec filtering

support.js
=> fix: update spec filter depending on the mask

.circleci/config.yml, scripts/check-coverage.js, scripts/only-covered.js
- closes #175
added custom scripts to check if all expected source files are covered at 100%, and no extra files are in the coverage results
=> add coverage check after same-folder example

.circleci/config.yml, README.md, cypress/plugins/index.js, examples/before-all-visit/cypress/plugins/index.js, examples/before-each-visit/cypress/plugins/index.js, examples/same-folder/plugins.js, examples/support-files/cypress/plugins/index.js, examples/ts-example/cypress/plugins/index.js, examples/use-plugins-and-support/README.md, examples/use-plugins-and-support/cypress.json, examples/use-plugins-and-support/cypress/integration/spec.js, examples/use-plugins-and-support/index.html, examples/use-plugins-and-support/main-instrumented.js, examples/use-plugins-and-support/main.js, examples/use-plugins-and-support/package-lock.json, examples/use-plugins-and-support/package.json, plugins.js, support.js, task.js
To avoid support hooks "blindly" trying to call `cy.task('resetCoverage')` and other hooks if the plugins has never registered them
BREAKING CHANGE: the task sets an environment variable and needs
to return its config. The new registration thus looks like this
```js
// your plugins file
module.exports = (on, config) => {
require('cypress/code-coverage/task')(on, config)
// IMPORTANT to return the config object
// with the any changed environment variables
return config
}
```
Support code can check variable `Cypress.env('codeCoverageTasksRegistered')`
before calling `cy.task`
closes #179
To disable any code coverage actions, set environment variable `coverage: false` in `cypress.json` or via environment variable or via CLI
=> feat: set flag from plugins task that they were registered

.circleci/config.yml, task.js
- closes #188
Before generating report, updates nyc results JSON file. If there is a non-absolute path, and file exists, changes the path to absolute. This puts files instrumented in different ways in the same report folder, allowing for better reports
=> feat: automatically resolve non-absolute paths to files

.circleci/config.yml, examples/exclude-files/.babelrc, examples/exclude-files/README.md, examples/exclude-files/cypress.json, examples/exclude-files/cypress/integration/spec.js, examples/exclude-files/cypress/plugins/index.js, examples/exclude-files/cypress/support/commands.js, examples/exclude-files/cypress/support/index.js, examples/exclude-files/index.html, examples/exclude-files/main.js, examples/exclude-files/package.json, examples/exclude-files/second.js, task.js
=> feat: read nyc report options from package 192

.circleci/config.yml, .github/ISSUE_TEMPLATE/bug_report.md, README.md, examples/ts-example/calc.ts, examples/ts-example/main.ts, examples/ts-example/package.json, package.json, task.js
- seems to work right away without extra configs
=> fix: simpler TypeScript advice

.circleci/config.yml, cypress/integration/filtering.js, cypress/integration/spec.js, package.json, support-utils.js, support.js, task-utils.js, task.js
=> fix: split utils into support and task utils

.circleci/config.yml, README.md, examples/use-webpack/.babelrc, examples/use-webpack/README.md, examples/use-webpack/cypress.json, examples/use-webpack/cypress/integration/spec.js, examples/use-webpack/cypress/plugins/index.js, examples/use-webpack/dist/index.html, examples/use-webpack/package.json, examples/use-webpack/src/calc.js, examples/use-webpack/src/index.js, examples/use-webpack/webpack.config.js, package-lock.json, package.json
=> Add simple webpack example

.circleci/config.yml, .nycrc.json, cypress/integration/combine-spec.js, package-lock.json, package.json, task-utils.js, task.js
=> feat: merge nyc options from multiple files

.circleci/config.yml, README.md, common-utils.js, cypress/integration/combine-spec.js, examples/all-files/.babelrc, examples/all-files/README.md, examples/all-files/cypress.json, examples/all-files/cypress/integration/spec.js, examples/all-files/cypress/plugins/index.js, examples/all-files/cypress/support/commands.js, examples/all-files/cypress/support/index.js, examples/all-files/index.html, examples/all-files/main.js, examples/all-files/not-covered.js, examples/all-files/package.json, examples/all-files/second.js, package-lock.json, package.json, task-utils.js, task.js
=> feat: find missing files when using all:true option

.github/ISSUE_TEMPLATE/bug_report.md, README.md, common-utils.js, cypress/integration/combine-spec.js, examples/exclude-files/package.json, task.js
- closes #217 
Could be relevant to any TypeScript project
=> fix: set excludeAfterRemap to false by default

support.js
- closes #209 
keeping existing LOG messages the same for now
=> feat: log all tasks using custom messages

.circleci/config.yml, common-utils.js, cypress/integration/combine-spec.js
which generates report in `coverage/coverage-summary.json` like
```json
{
"total": {
"lines": {
"total": 3,
"covered": 3,
"skipped": 0,
"pct": 100
},
"statements": {
"total": 3,
"covered": 3,
"skipped": 0,
"pct": 100
},
"functions": {
"total": 1,
"covered": 1,
"skipped": 0,
"pct": 100
},
"branches": {
"total": 0,
"covered": 0,
"skipped": 0,
"pct": 100
}
},
"/Users/gleb/git/instrument-example/src/App.js": {
"lines": {
"total": 1,
"covered": 1,
"skipped": 0,
"pct": 100
},
"functions": {
"total": 1,
"covered": 1,
"skipped": 0,
"pct": 100
},
"statements": {
"total": 1,
"covered": 1,
"skipped": 0,
"pct": 100
},
"branches": {
"total": 0,
"covered": 0,
"skipped": 0,
"pct": 100
}
},
"/Users/gleb/git/instrument-example/src/index.js": {
"lines": {
"total": 2,
"covered": 2,
"skipped": 0,
"pct": 100 …
```
=> feat: add json summary report

common-utils.js, cypress/integration/combine-spec.js, package-lock.json, package.json, task-utils.js
This PR adds support for reading NYC configuration from `.nycrc.yaml`, `.nycrc.yml`, and `nyc.config.js`.
According to the [NYC docs](https://github.com/istanbuljs/nyc#configuration-files), these well-known filenames are valid place to store NYC configuration, and it's best to be comprehensive. (It's surprising to users when they think NYC is being configured properly, but it's not being read by this plugin.)
=> feat: add support for other NYC configuration files

task.js
=> fix: move nyc require to only when needed

.circleci/config.yml, examples/all-files/package.json
to make sure we support windows paths correctly
=> chore: adding CI test on Windows

task.js
After configuring nyc with
```
"report-dir": "cypress/test-results/coverage",
"reporter": "json",
"temp-dir": "cypress/test-results/coverage/.nyc_output"
```
I observed the following error when starting the tests in a fresh repo clone:
This PR fixes this by recursively creating all subfolders that are needed to satisfy the config.
=> fix: add recursive=true to mkdirSync when creating output folder

.circleci/config.yml, README.md, examples/unit-tests-js/.babelrc, examples/unit-tests-js/README.md, examples/unit-tests-js/cypress.json, examples/unit-tests-js/cypress/integration/spec.js, examples/unit-tests-js/cypress/plugins/index.js, examples/unit-tests-js/cypress/support/index.js, examples/unit-tests-js/package.json, examples/unit-tests-js/src/utils/misc.js
=> add example with just unit test code coverage

README.md, examples/unit-tests-ts/.babelrc, examples/unit-tests-ts/README.md, examples/unit-tests-ts/cypress.json, examples/unit-tests-ts/cypress/integration/spec.ts, examples/unit-tests-ts/cypress/plugins/index.js, examples/unit-tests-ts/cypress/support/index.js, examples/unit-tests-ts/package.json, examples/unit-tests-ts/src/utils/misc.ts, examples/unit-tests-ts/tsconfig.json, package-lock.json, package.json
reproducible example for #361
If the source files are using TypeScript, then they are not instrumented when using our Browserify preprocessor. As soon as we set `options.typescript = require.resolve('typescript')` the Istanbul plugin is ignored and the Spec iframe has no `window.__coverage__` object
=> hmm, could not TS work example

package-lock.json, package.json, support.js
Cypress.moment() will be removed in upcoming 7.0 release
=> Remove call to deprecated Cypress.moment()

.github/workflows/snyk_sca_scan.yaml, .github/workflows/snyk_static_analysis_scan.yaml
This PR adds security controls in support of vulnerability scanning for third party packages as well as first party code. Snyk is already implemented, but these actions bring the Cypress Tools into alignment with our vulnerability management strategy. The actions that this pull request introduces send the scan results back to the Snyk dashboard. The Snyk dashboard is then coupled with branch protection rules that dictate our levels of protection by blocking PRs where this git action fails as a check.
Once the solution is fully implemented, the failures you see on the PR related to this would prevent merges of the code to the 'develop' and 'master' branches. The exit status it failed with today indicates that there is a critical vulnerability in the code base. This PR aims to increase this …
=> SEC-229 | Initial commit git actions

.circleci/config.yml
- updates the cypress orb to v3, which allows ours CI job to continue running by implicitly upgrading the install version of node from v12 to v16
- also bumps the windows orbs to latest to get a non broken version of `windows-nvm`
=> chore: update cypress and windows orb

task.js
Just a quick typo fix ("by" -> "be") in the error message thrown when the nyc `exclude` option value is not an array.
=> Update nyc options "exclude" error message

task-utils.js
When writing an application with `"type": "module"` in `package.json`, it becomes _impossible_ to set the NYC config with JS, since it only supports the `.js` extension and it only supports CommonJS. As a result, any configuration in `nyc.config.js` will fail for trying to `require` an ES module.
This PR adds support for `nyc.config.cjs`, allowing packages with `"type": "module"` to still configure a `nyc.config.cjs` file for a CommonJS configuration.
=> feat: support CJS configs in ES packages

package.json, task.d.ts
```
/.../cypress/plugins/index.ts
13:3  error  Unsafe call of an `any` typed value  @typescript-eslint/no-unsafe-call
```
I've been copy-pasting this between repos, which is a poor developer experience, but it's also now not working in monorepos, because it's existence in the root directory is not picked up by the workspace-specific linter.
```typescript
declare module '@cypress/code-coverage/task' {
import 'cypress';
export default function registerCodeCoverageTasks(
on: Cypress.PluginEvents,
// eslint-disable-next-line @typescript-eslint/prefer-readonly-parameter-types
config: Cypress.PluginConfigOptions,
): void;
}
```
The aim of this PR is to apply the workaround solution to this repository such that the workaround is no longer required.
=> add TypeScript definition to task.js

.github/ISSUE_TEMPLATE/bug_report.md, README.md, cypress/README.md
When I using the readme file, I clicked on a link, and it 404ed.
So, in this PR, I've checked the links in the markdown file, spellchecked it, and linted the markdown files.
I hope that I did not introduce any errors in the documentation. 
I'm always open to feedback and will answer any questions you might have.
=> linting and spellchecking the markdown files

.github/workflows/snyk_sca_scan.yaml
Excluding test apps from snyk. These are only used for example and testing purposes. 
The snyk scans have been failing due to some react-script in the test apps. I don't think this is important to highlight.
=> exclude test-apps from snyk

README.md
Closes https://github.com/cypress-io/code-coverage/issues/701
=> Update Readme with v10 instructions

support-utils.js
Optimize for fewer regex executions. I'm actually wondering if the regex is even necessary.
=> fix: Check for inputSourceMap existing before regex execution

.circleci/config.yml, README.md, support.js, test-apps/multiple-backends/.babelrc, test-apps/multiple-backends/README.md, test-apps/multiple-backends/cypress.config.js, test-apps/multiple-backends/cypress/e2e/spec.cy.js, test-apps/multiple-backends/cypress/plugins/index.js, test-apps/multiple-backends/cypress/support/e2e.js, test-apps/multiple-backends/package.json, test-apps/multiple-backends/server/index.html, test-apps/multiple-backends/server/server-3003.js, test-apps/multiple-backends/server/server-3004.js
Closes https://github.com/cypress-io/code-coverage/issues/349
=> feat: support multiple servers from which to gather code coverage

support.js
=> fix: ensure that projects without optional chainer support can use @cypress/code-coverage

.circleci/config.yml, README.md, support-utils.js, support.js, test-apps/batch-send-coverage/.babelrc, test-apps/batch-send-coverage/README.md, test-apps/batch-send-coverage/cypress.config.js, test-apps/batch-send-coverage/cypress/e2e/spec.cy.js, test-apps/batch-send-coverage/cypress/plugins/index.js, test-apps/batch-send-coverage/cypress/support/commands.js, test-apps/batch-send-coverage/cypress/support/e2e.js, test-apps/batch-send-coverage/index.html, test-apps/batch-send-coverage/main.js, test-apps/batch-send-coverage/package-lock.json, test-apps/batch-send-coverage/package.json, test-apps/batch-send-coverage/second.js, test-apps/batch-send-coverage/third.js
Some users, including myself, have experienced task timeouts when large coverage reports are sent to the Node process. This change
- Adds support for environment variable `sendCoverageBatchSize`
- Adds a support utility function for retrieving and validating the variable
- Sends coverage to Node backend in batches of size `sendCoverageBatchSize` only if the environment variable is set and valid
This may address issue #455 
In the existing full-report scenario, I was experiencing timeouts even when setting `taskTimeout` to 10+ minutes. With these changes, the coverage report is successfully constructed in seconds.
=> Batch coverage data sent to combineCoverage to prevent timeouts

package.json
- Closes https://github.com/cypress-io/code-coverage/issues/938
This was changed in webpack-preprocessor: https://github.com/cypress-io/cypress/pull/31218 and should be reflected here as well.
=> Allow babel-loader v10 as peer-dependency
